clients_num: 10
BLOCK_LENGTH: 2048
SH_MAX_ORDER: 2
IR_TRUNCATION_LEVEL: -60
REMOTE_OSC_PORT: 5100
monitoring:
    name: monitoring
    starting_output_channel: 62
    output_channel_count: 2
    osc_port: 5005
microphones: 
    - 
        name: 1_0_deg
        starting_input_channel: 2
        input_channel_count: 8
        starting_output_channel: 42
        output_channel_count: 2
        azim_deg: 0
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
    - 
        name: 1_90_deg
        starting_input_channel: 2
        input_channel_count: 8
        starting_output_channel: 44
        output_channel_count: 2
        azim_deg: 90
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
    - 
        name: 2_0_deg
        starting_input_channel: 10
        input_channel_count: 8
        starting_output_channel: 46
        output_channel_count: 2
        azim_deg: 0
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
    - 
        name: 2_90_deg
        starting_input_channel: 10
        input_channel_count: 8
        starting_output_channel: 48
        output_channel_count: 2
        azim_deg: 90
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
    - 
        name: 3_0_deg
        starting_input_channel: 18
        input_channel_count: 8
        starting_output_channel: 50
        output_channel_count: 2
        azim_deg: 0
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
    - 
        name: 3_90_deg
        starting_input_channel: 18
        input_channel_count: 8
        starting_output_channel: 52
        output_channel_count: 2
        azim_deg: 90
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
    - 
        name: 4_0_deg
        starting_input_channel: 26
        input_channel_count: 8
        starting_output_channel: 54
        output_channel_count: 2
        azim_deg: 0
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
    - 
        name: 4_90_deg
        starting_input_channel: 26
        input_channel_count: 8
        starting_output_channel: 56
        output_channel_count: 2
        azim_deg: 90
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
    - 
        name: 5_0_deg
        starting_input_channel: 34
        input_channel_count: 8
        starting_output_channel: 58
        output_channel_count: 2
        azim_deg: 0
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
    - 
        name: 5_90_deg
        starting_input_channel: 34
        input_channel_count: 8
        starting_output_channel: 60
        output_channel_count: 2
        azim_deg: 90
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"